app/views/main_views.py
import json
import requests

from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from flask_user import current_user, login_required, roles_required

from app import db
from app.models.user_models import UserProfileForm

main_blueprint = Blueprint('main', __name__, template_folder='templates')

'''
Customer-specific configuration is required for these fields:
'''
base64_encoded_username_and_password = '<add your base64-encoded username:password here>'
headers = {'Authorization': 'Basic ' + base64_encoded_username_and_password}

'''
URL parameters
'''
account_id = '<Your Bandwidth Account Number>'

'''
POST body parameters
'''
messaging_application_id = '<Your Bandwidth Messaging Application ID>'
from_phone_num = '<Your Source Telephone Number in E164 format>'


# The Home page is accessible to anyone
@main_blueprint.route('/')
def home_page():
    return render_template('main/home_page.html')


@main_blueprint.route('/2fa', methods=['GET', 'POST'])
def two_factor_auth_page():
    to_phone_num = '<look up the User telephone number, or hard-code one for testing, number must be in in E164 format>'
    data = json.dumps({
        "applicationId": messaging_application_id,
        "scope": "example",
        "to": to_phone_num,
        "from": from_phone_num
    })
    requests.post(f'https://mfa.bandwidth.com/api/v1/accounts/{account_id}/code/messaging', headers=headers, data=data)
    flash('You must verify the authentication code you received. Enter it here:', 'success')
    return render_template('main/2fa_page.html')


@main_blueprint.route('/verify_2fa', methods=['GET', 'POST'])
def verify_two_factor_auth_page():
    to_phone_num = '<look up the User telephone number, or hard-code one for testing, number must be in in E164 format>'
    data = json.dumps({
        "applicationId": messaging_application_id,
        "scope": "example",
        "to": to_phone_num,
        "from": from_phone_num,
        "code": request.form["two_factor_code"]
    })
    resp = requests.post(f'https://mfa.bandwidth.com/api/v1/accounts/{account_id}/code/verify', headers=headers, data=data)
    resp_dict = resp.json()
    if (resp.status_code == 200) and isinstance(resp_dict, dict) and resp_dict.get('valid'):
        return redirect(url_for('main.member_page'))
    else:
        # session.pop('_flashes', None)
        flash('That code is invalid, please try again.')
        return redirect(url_for('user.login'))


# The User page is accessible to authenticated users (users that have logged in)
@main_blueprint.route('/member')
@login_required  # Limits access to authenticated users
def member_page():
    return render_template('main/user_page.html')


# The Admin page is accessible to users with the 'admin' role
@main_blueprint.route('/admin')
@roles_required('admin')  # Limits access to users with the 'admin' role
def admin_page():
    return render_template('main/admin_page.html')


@main_blueprint.route('/main/profile', methods=['GET', 'POST'])
@login_required
def user_profile_page():

    # Initialize form
    form = UserProfileForm(request.form, obj=current_user)

    # Process valid POST
    if request.method == 'POST' and form.validate():

        # Copy form fields to user_profile fields
        form.populate_obj(current_user)

        # Save user_profile
        db.session.commit()

        # Redirect to home page
        return redirect(url_for('main.home_page'))

    # Process GET or invalid POST
    return render_template('main/user_profile_page.html', form=form)

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- These 3 meta tags MUST come first -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- These 3 meta tags MUST come first -->

        <title>2FA Sample Customer App</title>

        <!-- Bootstrap CSS and JS -->
        <link href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="{{ url_for('static', filename='bootstrap/js/html5shiv.min.js') }}"></script>
            <script src="{{ url_for('static', filename='bootstrap/js/respond.min.js') }}"></script>
        <![endif]-->

        <!-- Application specific CSS-->
        <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css') }}">
    </head>
    <body>
        {% block body %}
        <!-- Application specific HTML -->
        <div id="header-div" class="clearfix with-margins">
            <div class="pull-left"><a href="/"><h1 class="no-margins">2FA Sample Customer App</h1></a></div>
            <div class="pull-right">
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('main.user_profile_page') }}">{{ current_user.first_name or current_user.username or current_user.email }}</a>
                    &nbsp; | &nbsp;
                    <a href="{{ url_for('user.logout') }}">Sign out</a>
                {% else %}
                    <a href="{{ url_for('user.login') }}">Sign in</a>
                {% endif %}
            </div>
        </div>
        <hr class="no-margins"/>

        <div id="main-div" class="with-margins">
        {% block pre_content %}{% endblock %}

        {# One-time system messages called Flash messages #}
        {% block flash_messages %}
            {%- with messages = get_flashed_messages(with_categories=true) -%}
                {% if messages %}
                    {% for category, message in messages %}
                        {% if category=='error' %}
                            {% set category='danger' %}
                        {% endif %}
                        <div class="alert alert-{{category}}">{{ message|safe }}</div>
                    {% endfor %}
                {% endif %}
            {%- endwith %}
        {% endblock %}

        {% block content %}{% endblock %}

        {% block post_content %}{% endblock %}
        </div>

        <br/>
        <hr class="no-margins"/>
        <div id="footer-div" class="clearfix with-margins">
            <div class="pull-left">{{ user_manager.USER_APP_NAME }}</div>
            <div class="pull-right">&copy; 2020 Bandwidth</div>
        </div>

        <!-- Bootstrap JS -->
        <script src="{{ url_for('static', filename='bootstrap/js/jquery.min.js') }}"></script>
        <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>

        <!-- Optional Google Analytics: change UA-XXXXX-X to be your site's ID.
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='https://www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
        -->
        {% endblock %}
    </body>
</html>